hw_5/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'signup', to: 'authors#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :authors
  resources :sessions

  resources :posts do
    resources :comments do
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end
    # do
    #   member do
    #     post :publish
    # #  end
    # end
  end
end

hw_5/app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :post
  belongs_to :author
  acts_as_votable
  has_ancestry
  validates :body, presence: true

  enum status: %i[unpublished published]

  # scope :published, -> { where(status: 1) }
  # scope :unpublished, -> { where(status: 0) }
end

hw_5/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_comment, only: %i[new edit show create update destroy]
  before_action :logged_in_author, only: %i[create destroy]

  def index
    @post.comments = @post.comments.arrange(order: :created_at)
  end

  def show
    @comment = @post.comments.find(params[:id])
  end

  def new
    @comment = Comment.new(parent_id: params[:parent_id])
  end

  def edit
    @comment = @post.comments.find(params[:id])
  end

  def create
    @comment = @post.comments.build(comment_params)
    @comment.author_id = current_user.id
    if @comment.ancestors.count <= 4
      respond_to do |format|
        if @comment.save
          format.js { render 'create', status: :created, location: @post }
          format.html { redirect_to @post, notice: 'Comment was successfully created.' }
        else
          format.html { redirect_to @post, alert: @comment.errors.full_messages.first }
        end
      end
    else
      respond_to do |format|
        format.html { redirect_to @post, alert: 'To much comments in one tree (5 comments max)' }
      end
    end
  end

  def update
    @comment = @post.comments.find(params[:id])
    respond_to do |format|
      if @comment.update(comment_params)
        format.js { render 'update', status: :created, location: @post }
        format.html { redirect_to @post, notice: 'Comment was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @comment = @post.comments.find(params[:id])
    @comment.destroy
    respond_to do |format|
      format.js { render 'destroy', status: :created, location: @post }
      format.html { redirect_to @post, notice: 'Comment was successfully destroyed.' }
    end
  end

  def publish
    @comment = @post.comments.find(params[:id])
    @comment.update(status: :published)
    redirect_to post_path(@post), notice: 'successfully published.'
  end

  def upvote
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.liked_by current_user
    respond_to do |format|
      format.js { render 'vote', status: :created, location: @post }
      format.html { redirect_to @post }
    end
  end

  def downvote
    @post = Post.find(params[:post_id])
    @comment = @post.comments.find(params[:id])
    @comment.downvote_from current_user
    respond_to do |format|
      format.js { render 'vote', status: :created, location: @post }
      format.html { redirect_to @post }
    end
  end

  private

  def set_comment
    @post = Post.find(params[:post_id])
  end

  def comment_params
    params.require(:comment).permit(:body, :author_id, :post_id, :parent_id)
  end

end

hw_5/app/helpers/comments_helper.rb
module CommentsHelper
  def nested_comments(comments)
    comments.map do |comment, sub_comments|
      render(comment) + content_tag(:div, nested_comments(sub_comments), class: 'nested_comments')
    end.join.html_safe
  end
end

hw_5/app/views/comments/_comment.html.erb
<div class="comment-<%= comment.id %>">
  <article class="blog-post">
    <p class="blog-post-meta">
      <%= avatar_for(@post.author, size: 30) %>
      <strong class="d-inline-block mb-2 text-primary"><%= comment.author.first_name %></strong></p>
    <p>
      <small class="text-muted"><%= distance_of_time_in_words(comment.created_at, Time.now) %></small>
      <br>
      <% if comment.created_at < comment.updated_at %><span class="edited" style="color: #cc0000;">edited</span>
      <% end %>
      <%= comment.body %></p>

    <%= comment.get_upvotes.size %>
    <%= link_to ('<i class="fa fa-thumbs-up"></i>').html_safe, like_post_comment_path(@post, comment),
                method: :put, :class => "btn btn-outline-dark shadow-none", id: 'upvote', :remote => true %>
    <%= comment.get_downvotes.size %>
    <%= link_to ('<i class="fa fa-thumbs-down"></i>').html_safe, dislike_post_comment_path(@post, comment),
                method: :put, :class => "btn btn-outline-dark shadow-none", id: 'downvote', :remote => true %>
    |
    <%= comment.votes_for.size %>
    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-suit-heart-fill" viewBox="0 0 16 16">
      <path class="btn shadow-none" d="M4 1c2.21 0 4 1.755 4 3.92C8 2.755 9.79 1 12 1s4 1.755 4 3.92c0 3.263-3.234 4.414-7.608 9.608a.513.513 0 0 1-.784 0C3.234 9.334 0 8.183 0 4.92 0 2.755 1.79 1 4 1z"/>
    </svg>
    <br>
    <br>
  </article>
  <% if comment.author == current_user %>

    <%= link_to 'Reply', new_post_comment_path(comment.post, :parent_id => comment.id, js: true), remote: true,
                class: 'btn btn-outline-warning shadow-none comment_reply', id: "reply-comment-#{comment.id}"%>

    <% if comment.created_at >= 1.hour.ago %>
      <%= link_to 'Edit', edit_post_comment_path(comment.post, comment, js: true),
                  remote: true, :class => "btn btn-outline-dark shadow-none", id: "edit_comment-#{comment.id}" %>
    <% end %>
    <%= link_to 'Destroy Comment', [comment.post, comment],
                data: { confirm: 'Are you sure?' },:class => "btn btn-outline-danger shadow-none", method: :delete, remote: true %>
  <% end %>
  <br>
  <br>
  <hr class="featurette-divider w-25 d-inline-block">
</div>

hw_5/app/views/comments/_form.html.erb
<%= form_for ([@post, @post.comments.build]), remote: true, local: false, class: "form_new" do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>
      <ul>
        <% @post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <% if session[:author_id] != current_user %>
    <div class="add_comment">
      <div class="form-group">
        <%= f.hidden_field :parent_id, value: params[:parent_id] %>
      </div>
      <div class="form-group">
        <%= f.hidden_field :author_id, :value => current_user.id %>
      </div>
      <div class="form-group ">
        <%= f.text_area :body, :rows => 5, :class => "form-control col-md-4 shadow-none" %>
      </div>
      <%= f.submit :class => "btn btn-outline-success shadow-none" %>
    </div>
  <% end %>
<% end %>

hw_5/app/views/comments/_form_edit.html.erb
<%= form_for([@post, @comment], remote: true) do |form| %>
  <% if @comment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@comment.errors.count, "error") %> prohibited this comment from being saved:</h2>

      <ul>
        <% @comment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <%= form.hidden_field :parent_id %>
  <p>
    <%= form.text_area :body, :rows => 5, class:'form-control col-md-4' %>
  </p>
  <p>
    <%= form.submit class:'btn btn-info' %>
  </p>
<% end %>

hw_5/app/views/comments/_new_form.html.erb
<%= form_with model: [ @post, @post.comments.build ], remote: true do |form| %>
  <%= form.hidden_field :parent_id, value: params[:parent_id] %>
  <p>
    <%= form.text_area :body, :rows => 5, class:'form-control col-md-4' %>
  </p>
  <p>
    <%= form.submit class:'btn btn-info btn-sm' %>
  </p>
<% end %>

hw_5/app/views/comments/create.js.erb
$("#comments").replaceWith("<div id='comments'><%= j nested_comments @post.comments.arrange%>")
$("#comments_form .form_new")[0].reset();

hw_5/app/views/comments/destroy.js.erb
$('.comment-<%= @comment.id %>').hide(500);

hw_5/app/views/comments/edit.html.erb
<%= render 'comments/form_edit' %>

hw_5/app/views/comments/edit.js.erb
$('#edit_comment-<%= params[:parent_id]%>').hide();

$(".comment-<%=@comment.id %>").after('<%= j render('form_edit', comment: @comment) %>');

hw_5/app/views/comments/new.html.erb
<%= render 'comments/new_form' %>

hw_5/app/views/comments/new.js.erb
$('.comment-reply').show()
$('.form_new').hide()
$('#reply-comment-<%= params[:parent_id]%>').hide();
$('#reply-comment-<%= params[:parent_id]%>').after('<%= j render 'form' %>');
$('#comments_form .form_new').hide()

hw_5/app/views/comments/update.js.erb
$("#comments").replaceWith("<div id='comments'><%= j nested_comments @post.comments.arrange(order: :created_at)%>")

hw_5/app/views/comments/vote.js.erb
$(".comment-<%= @comment.id %>").replaceWith('<%= j render partial:'comments/comment', locals: {comment: @comment} %>');