hw_5/config/routes.rb
Rails.application.routes.draw do
  root 'posts#index'
  get 'signup', to: 'authors#new', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :authors
  resources :sessions

  resources :posts do
    resources :comments do
      member do
        put "like", to: "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end
    # do
    #   member do
    #     post :publish
    # #  end
    # end
  end
end

hw_5/app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: %i[show edit update destroy]
  before_action :logged_in_author, only: %i[create destroy]
  before_action :correct_user, only: :destroy
  before_action :add_view, only: %i[index show]


  def index
    @post = current_user.posts.build if logged_in?
    @posts = if params[:search]
               Post.search(params[:search]).order('created_at DESC').paginate(page: params[:page], per_page: 8)
             else
               Post.all.order('created_at DESC').paginate(page: params[:page], per_page: 8)
             end
  end

  def show
    @comments = @post.comments
    @post.increment!(:views)
  end

  def new
    @post = Post.new
  end

  def edit; end

  def create
    @post = current_user.posts.build(post_params)
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search; end

  private

  def set_post
    @post = Post.find(params[:id])
  end

  def post_params
    params.require(:post).permit(:title, :content, :photo, :author_id)
  end

  def correct_user
    @post = current_user.posts.find_by(id: params[:id])
    redirect_to root_url if @post.nil?
  end

  def add_view
    unless current_user
      cookies[:views] = cookies[:views].present? ? cookies[:views].to_i + 1 : 1
      @pls_register = cookies[:views].to_i % 5 == 0
    end
  end
end

hw_5/app/helpers/posts_helper.rb
module PostsHelper
end

hw_5/app/views/posts/_form.html.erb
<%= form_with(model: post) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
        <% post.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :title, :class => "form-label" %>
    <%= form.text_field :title, :class => "form-control shadow-none" %>
  </div>

  <div class="form-group">
    <%= form.label :content, :class => "form-label" %>
    <%= form.text_area :content, :rows => 5, :class => "form-control shadow-none" %>
  </div>

  <div class="form-group">
    <%= form.label :photo, :class => "form-label" %>
    <%= form.file_field :photo %>
  </div>

  <%= form.submit :class => "btn btn-outline-success shadow-none" %>
<% end %>

hw_5/app/views/posts/_header.html.erb
<header>
  <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
    <div class="container-fluid">
      <a><%= link_to 'Blog RoR', posts_path, :class => "navbar-brand" %></a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav me-auto mb-2 mb-md-0">
          <li class="nav-item active">
            <a><%= link_to 'Home', posts_path, :class => "nav-link" %></a>
          </li>
          <% if logged_in? %>
            <li class="nav-item">
              <a><%= link_to 'New Post', new_post_path, :class => "nav-link" %></a>
            </li>
            <li>
              <a><%= link_to 'Users', authors_path, :class => "nav-link" %></a>
            </li>
          <% end %>
        </ul>
      </div>
      <% if logged_in? %>

        <div id="fat-menu" class="dropdown">
          <a href="#" class="dropdown-toggle text-light" data-toggle="dropdown">
            <%= avatar_for(current_user, size: 40) %> <b class="caret"></b>
          </a>
          <ul class="dropdown-menu bg-dark">
            <li><%= link_to "Profile author", current_user, :class => "text-light m-4" %></li>
            <br>
            <li><%= link_to "Settings author", edit_author_path(current_user), :class => "text-light m-4" %></li>
            <br>
            <li class="divider"></li>
            <li>
              <%= link_to "Log Out", logout_path, method: "get", :class => "text-light m-4" %>
            </li>
          </ul>
        </div>
      <% else %>
        <%= link_to "Sign Up ", signup_path, :style => "color: #fff" %> <span style="color: #fff;margin: 0 5px;"> or </span>
        <%= link_to " Log In", login_path, :style => "color: #fff" %>
      <% end %>
      <%= form_tag(posts_path, :method => "get", id: "search-form", class: "d-flex") do %>
        <%= text_field_tag :search, params[:search], class: "form-control m-2 shadow-none", placeholder: "Search Posts" %>
        <%= submit_tag "Search", class: "btn btn-outline-success m-2" %>
      <% end %>

    </div>
  </nav>
</header>

hw_5/app/views/posts/_modal.html.erb
<% if @pls_register %>
  <div id="myModal" class="modal" style="width: 50%; margin: 0 auto; right: 0;">
    <div class="modal-content">
      <div class="modal-header">
        <span class="close" style="position: relative; top: 7px; left: -10px;">&times;</span>
        <h2> Hi guest</h2>
      </div>
      <div class="modal-body">
        <p>Please log in or register otherwise I'll get you)</p>
      </div>
      <div class="modal-footer">
        <%= link_to "Sign Up", signup_path %> or
        <%= link_to "Log In", login_path %>
      </div>
    </div>
  </div>
  <script>
      $(function () {
          $("#myModal").show()
          $('.close').click(function () {
              $("#myModal").css("display", "none")
          });
      })
  </script>
<% end %>

hw_5/app/views/posts/edit.html.erb
<div class="p-4 p-md-5 mb-4">
  <div class="px-0 p-4">
    <h1 class="display-4 font-italic text-center">Edit Post</h1>
  </div>
</div>
<div class="container">
  <div class="row justify-content-center align-items-center h-100">
    <div class="col col-sm-6 col-md-6 col-lg-4 col-xl-3">
      <%= render 'form', post: @post %>
      <br>
      <%= link_to 'Show', @post, :class => "btn btn-outline-dark shadow-none" %>
      <%= link_to 'Back', posts_path, :class => "btn btn-outline-dark shadow-none" %>
    </div>
  </div>
</div>

hw_5/app/views/posts/index.html.erb
<p id="notice" class="notice"><%= notice %></p>

<%= render 'modal'%>
<div class="p-4 p-md-5 mb-4">
  <div class="px-0 p-4">
    <h1 class="display-4 font-italic text-center">Title of a longer featured blog post</h1>
  </div>
</div>

<% @posts.each do |post| %>
  <main>
    <div class="container marketing">
      <hr class="featurette-divider">
      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">
            <%= avatar_for(post.author, size: 40) %>
            <%= post.author.first_name %>
            <br>
            <span class="text-muted"><%= post.title %></span></h2>
          <p><i><%= post.content %></i></p>
        </div>
        <div class="col-md-5 text-right">
          <%#= image_tag(post.image, :class => "img-thumbnail img-fluid") %>
          <% if post.photo.present? %>
            <p><%= image_tag post.photo.url(:medium) %></p>
          <% end %>
        </div>
        <div class="viewing m-2">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-eye" viewBox="0 2 16 16">
            <path fill-rule="evenodd" d="M16 8s-3-5.5-8-5.5S0 8 0 8s3 5.5 8 5.5S16 8 16 8zM1.173 8a13.134 13.134 0 0 0 1.66 2.043C4.12 11.332 5.88 12.5 8 12.5c2.12 0 3.879-1.168 5.168-2.457A13.134 13.134 0 0 0 14.828 8a13.133 13.133 0 0 0-1.66-2.043C11.879 4.668 10.119 3.5 8 3.5c-2.12 0-3.879 1.168-5.168 2.457A13.133 13.133 0 0 0 1.172 8z"/>
            <path fill-rule="evenodd" d="M8 5.5a2.5 2.5 0 1 0 0 5 2.5 2.5 0 0 0 0-5zM4.5 8a3.5 3.5 0 1 1 7 0 3.5 3.5 0 0 1-7 0z"/>
          </svg>
          <span class="badge" style="font-size: 1rem;"><%= post.views %></span>
        </div>

        <div class="comments-b m-2">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-fill" viewBox="0 1 16 16">
            <path d="M8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6-.097 1.016-.417 2.13-.771 2.966-.079.186.074.394.273.362 2.256-.37 3.597-.938 4.18-1.234A9.06 9.06 0 0 0 8 15z"/>
          </svg>
          <span class="badge" style="font-size: 1rem;"><%= post.comments.count %></span>
        </div>

        <div class="comments-time m-2">
          <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-alarm" viewBox="0 1 16 16">
            <path d="M8.5 5.5a.5.5 0 0 0-1 0v3.362l-1.429 2.38a.5.5 0 1 0 .858.515l1.5-2.5A.5.5 0 0 0 8.5 9V5.5z"/>
            <path d="M6.5 0a.5.5 0 0 0 0 1H7v1.07a7.001 7.001 0 0 0-3.273 12.474l-.602.602a.5.5 0 0 0 .707.708l.746-.746A6.97 6.97 0 0 0 8 16a6.97 6.97 0 0 0 3.422-.892l.746.746a.5.5 0 0 0 .707-.708l-.601-.602A7.001 7.001 0 0 0 9 2.07V1h.5a.5.5 0 0 0 0-1h-3zm1.038 3.018a6.093 6.093 0 0 1 .924 0 6 6 0 1 1-.924 0zM0 3.5c0 .753.333 1.429.86 1.887A8.035 8.035 0 0 1 4.387 1.86 2.5 2.5 0 0 0 0 3.5zM13.5 1c-.753 0-1.429.333-1.887.86a8.035 8.035 0 0 1 3.527 3.527A2.5 2.5 0 0 0 13.5 1z"/>
          </svg>
          <span class="badge" style="font-size: 1rem;"><%= distance_of_time_in_words(post.created_at, Time.now) %></span>
        </div>
        <div class="btn-group" role="group" aria-label="Basic outlined example">
          <%= link_to 'Show', post, :class => "btn btn-outline-dark shadow-none" %>
          <% if post.author == current_user %>
            <%= link_to 'Edit', edit_post_path(post), :class => "btn btn-outline-dark shadow-none" %>
            <%= link_to 'Destroy', post, method: :delete, data: {confirm: 'Are you sure?'}, :class => "btn btn-outline-dark shadow-none" %>
          <% end %>
        </div>
      </div>
      <hr class="featurette-divider">

    </div>
  </main>
<% end %>
<div class="row justify-content-center align-items-center">
  <div class="col col-sm-6 col-md-6 col-lg-4 col-xl-3">
  <%= will_paginate @posts, renderer: WillPaginate::ActionView::BootstrapLinkRenderer %>
  </div>
</div>

hw_5/app/views/posts/new.html.erb
<div class="p-4 p-md-5">
  <div class="px-0 p-4">
    <h1 class="display-4 font-italic text-center">New Post</h1>
  </div>
</div>

<div class="container">
  <div class="row justify-content-center align-items-center">
    <div class="col col-sm-6 col-md-6 col-lg-4 col-xl-3">
      <%= render 'form', post: @post %>
      <br>
      <%= link_to 'Back', posts_path, :class => "btn btn-outline-dark shadow-none" %>
    </div>
  </div>
</div>

hw_5/app/views/posts/show.html.erb
<p id="notice"><%= notice %></p>


<div class="p-4 p-md-5 mb-4">
  <div class="px-0 p-4">
    <h1 class="display-4 font-italic text-center">Show Post</h1>
  </div>
</div>

<div class="container">
  <div class="col-md-12">
    <div class="row g-0 border rounded overflow-hidden flex-md-row mb-4 shadow-sm h-md-250 position-relative">
      <div class="col p-4 d-flex flex-column position-static">
        <h2 class="featurette-heading">
          <%= avatar_for(@post.author) %>
          <%= @post.author.first_name %>
        </h2>
        <h3 class="mb-0"><%= @post.title %></h3>
        <div class="mb-1 text-muted"><%= distance_of_time_in_words(@post.created_at, Time.now) %></div>
        <p class="card-text mb-auto"><%= @post.content %></p>
      </div>
      <div class="col-auto d-none d-lg-block">
        <% if @post.photo.present? %>
          <p><%= image_tag @post.photo.url(:medium) %></p>
        <% end %>
      </div>
    </div>
  </div>
  <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-chat-fill" viewBox="0 1 16 16">
    <path d="M8 15c4.418 0 8-3.134 8-7s-3.582-7-8-7-8 3.134-8 7c0 1.76.743 3.37 1.97 4.6-.097 1.016-.417 2.13-.771 2.966-.079.186.074.394.273.362 2.256-.37 3.597-.938 4.18-1.234A9.06 9.06 0 0 0 8 15z"/>
  </svg>
  <span class="badge" style="font-size: 1rem;"><%= @post.comments.count %></span>
  <br>
  <br>
  <div id="comments">
    <%= nested_comments @post.comments.arrange(order: :created_at) %>
  </div>
  <div id="comments_form">
    <%= render 'comments/form' %>
  </div>
  <br>
  <%= link_to 'Back', posts_path, :class => "btn btn-outline-dark shadow-none" %>
  <span class="p-4"></span>
</div>